### PR TITLE
Remove first run/post update tracking

### PR DESCRIPTION
**Pull request by brainscar**
Remove first run/post update tracking

### CODE REVIEW

**Comment by intika** [comment]
Let me just double check that this is not already added in the cfg 
Thanks for your contribution it's appreciated :)

**Comment by intika** [comment]
Do you know what about:config setting does it change ?
And if the policy is available on ESR (librefox policy have to be compatible with ESR as well)
I am building new binaries i will look into this once done ;)

**Comment by brainscar** [comment]
Hi :)

Thank you for your hard work!

> Do you know what about:config setting does it change ?

I think it's **startup.homepage_override_url**

http://kb.mozillazine.org/Startup.homepage_override_url

This one is for new profiles:

**startup.homepage_welcome_url**

This one toggles the override:

**browser.startup.firstrunSkipsHomepage**

And the default homepage is set at:

**browser.startup.homepage**

:-)

**Comment by intika** [comment]
i will merge this but i will enable it later need to do some testing. 
thanks a lot for your contribution you rock !

**Comment by intika** [comment]
as promised i am looking at your pr now... 
this "OverrideFirstRunPage": "", is not necessary as it does not violate privacy and is already implemented in mozilla.cfg 
this "OverridePostUpdatePage": "", is kept, thank you for reporting this, and will probably updated to future Librefox update page...  
i am updating the repo...

**Pull request merged**
