### PR TITLE
Not "official" Firefox

### PR DESCRIPTION
**Pull request by yoasif**
This is not an "official" version of Firefox, so remove the "official" from the headline.

### CODE REVIEW

**Comment by Atavic** [comment]
It is a modification of the official firefox release:
https://github.com/intika/Librefox-Firefox#building-and-packaging-

**Comment by yoasif** [comment]
This repo was shared on the Firefox subreddit, and one of the top voted [comments](https://www.reddit.com/r/firefox/comments/a7zygm/librefoxfirefox_librefox_official_firefox_with_a/ec72794/) is 

>This is not an official Firefox project.

You can see how this is confusing. Official is not required to make the points you are trying to make (notwithstanding the fact that Firefox is already libre software).

**Comment by Atavic** [comment]
That mozilla guy says that this repo is not an official mozilla project. He's right.

Intika README says this is official firefox (application). Intika is also right.

Nowhere here is said that Librefox-Firefox is an official Mozilla project, like [these](https://wiki.mozilla.org/Projects)

**Comment by yoasif** [comment]
>Intika README says this is official firefox (application). Intika is also right.

I don't think that is true, since only Mozilla can release official builds. The packages available for download are modified - hence, not official.

**Comment by Atavic** [comment]
> you can instead say "modifications to official"

I agree with that.

**Comment by yoasif** [comment]
Modified my PR.

**Comment by intika** [comment]
Thanks for your contribution i finally get all the (15) new 2.1 packages ready i am publishing that now... and i will also change the "official" word. 
i agree this could be confusing.

**Pull request merged**
